### ISSUE TITLE
Migration to go modules

### ISSUE THREAD

**Issue by masch** [mcubik/goverreport#15]
Hey! @mcubik

What do you think about if the dependencies management project should be migrated with `go modules`?
Are you welling to accept a PR?

Thanks!

**Comment by mcubik** [comment]
Definitely, the project needs to be migrated to `modules`. Go ahead with the MR.

Thank you for contributing.

**Comment by masch** [comment]
Great! 
Let me know what you think on #16 PR.

**Comment by marco-m** [comment]
hello, it seems that this issue can be closed due to #16 :-)

**Comment by mcubik** [comment]
@marco-m You're right. Closed, thanks :)
