### ISSUE TITLE
thresholdType in .govverreport.yml is never considered  as metric

### ISSUE THREAD

**Issue by preethi29** [mcubik/goverreport#5]
`metric` command line args has default value as `block`.
So the `if` block which assigns thresholdType when metric is not empty (https://github.com/mcubik/goverreport/blob/master/main.go#L64) never fails and always considers only the command line args.

Also the documentation for .govverreport.yml is not updated with thresholdType. It still has `metric` as the key.

**Comment by mcubik** [comment]
:+1: 
Regarding `goverreport.yml` documentation: I originally used the name `thresholdType` and later came up with what I thought was a better name: `metric`. As you correctly pointed out, the configuration file is still using the old key `thesholdType` instead of `metric`. I created the issue #7.

**Comment by preethi29** [comment]
@mcubik I have raised a PR for this issue: https://github.com/mcubik/goverreport/pull/6

**Comment by mcubik** [comment]
@preethi29 In the branch issue/5-configured-metric-ignored I sketched an alternative solution which avoids making the `metric` argument mandatory (actually, the default value was still working but it was retrieved indirectly through the "default configuration", which I realized was unclear). 
Would you check it out?
